http:
  routers:
    home-assistant:
      rule: "Host(`home-assistant.noassl.at`)"
      entryPoints: "websecure"
      service: home-assistant
  services:
    home-assistant:
      loadBalancer:
        servers:
          - url: {{ env "HOMEASSISTANT_IP" }}
